[project]
name = "movie-genre-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "polars>=1.44.1",
    "torch==2.11.0",
    "transformers[torch]>=5.5.0",
    "numpy>=2.0.0",
    "accelerate>=1.14.0",
    "onnxscript>=0.7.1",
    "python-dotenv>=1.1.0",
    "matplotlib>=3.11.1",
    "pymongo>=4.0.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.workspace]
members = [
    "test123",
]
